@startuml mediastreaminterface
interface MediaSourceInterface
interface MediaStreamTrackInterface
interface VideoTrackSourceInterface
interface AudioProcessorInterface
interface VideoSinkInterface
interface VideoTrackInterface

interface AudioTrackSinkInterface
interface AudioSourceInterface
interface AudioTrackInterface
interface MediaStreamInterface

interface StreamCollectionInterface

class Notifier
class MediaStream
class MediaStreamTrack
class AudioTrack
class VideoTrack
class LocalAudioSource
class RemoteAudioSource

class VideoTrackSource
class VideoCapturerTrackSource
class VideoRtpTrackSource

class StreamCollection

MediaSourceInterface <|-- VideoTrackSourceInterface

MediaStreamTrackInterface <|-- VideoTrackInterface
VideoSinkInterface <--* VideoTrackInterface
VideoTrackSourceInterface <--* VideoTrackInterface

MediaSourceInterface <|-- AudioSourceInterface
MediaStreamTrackInterface <|-- AudioTrackInterface
AudioTrackSinkInterface <--* AudioSourceInterface
AudioTrackSinkInterface <--* AudioTrackInterface
AudioProcessorInterface <--* AudioTrackInterface
AudioSourceInterface <--* AudioTrackInterface

Notifier <|-- MediaStream

AudioTrackInterface <|-- MediaStreamTrack
VideoTrackInterface <|-- MediaStreamTrack
MediaStreamTrack <|-- AudioTrack
MediaStreamTrack <|-- VideoTrack

AudioSourceInterface <|-- LocalAudioSource
AudioSourceInterface <|-- RemoteAudioSource

VideoTrackSourceInterface <|-- VideoTrackSource
VideoTrackSource <|-- VideoCapturerTrackSource
VideoTrackSource <|-- VideoRtpTrackSource

StreamCollectionInterface <|-- StreamCollection
@enduml